print ("==============")
print ("BIODATA SAYA")
print ("==============")
print ("Nama : M.Fahmi Fauzi S")
print ("Nama Panggilan : Fahmi / Fauzi")
print ("NIM : 312110112")
print ("Hobby : Ngegame")
print ("Tempat tanda lahir : Jakarta, 06 Juni 2002")
print ("Umur : 19 tahun")
print ("Alamat : Perumaha Griya Hegar Asri Blok C9 No.6G, Cikarang Pusat, Kab.Bekasi")
print (" Telepon : 081286884679")
